// <auto-generated />
using System;
using Avw.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Avw.Data.Migrations
{
    [DbContext(typeof(AvwDbContext))]
    [Migration("20260920141028_AddCommunitySearch")]
    partial class AddCommunitySearch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Avw.Data.Entities.AppUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("EmailHash")
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("EmailHash");

                    b.HasIndex("Subject")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Avw.Data.Entities.Article", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint");

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Excerpt")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("FeatureOnHomepage")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("FeaturedMediaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PublishedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ScheduledUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SeoDescription")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("SeoTitle")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FeaturedMediaId");

                    b.HasIndex("ParentId");

                    b.HasIndex("Kind", "Slug")
                        .IsUnique();

                    b.HasIndex("Status", "ScheduledUtc");

                    b.HasIndex("Kind", "Status", "PublishedUtc");

                    b.ToTable("articles", (string)null);
                });

            modelBuilder.Entity("Avw.Data.Entities.ArticleRevision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("ArticleId")
                        .HasColumnType("bigint");

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RevisionNo")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ArticleId", "RevisionNo")
                        .IsUnique();

                    b.ToTable("article_revisions", (string)null);
                });

            modelBuilder.Entity("Avw.Data.Entities.ArticleTag", b =>
                {
                    b.Property<long>("ArticleId")
                        .HasColumnType("bigint");

                    b.Property<long>("TagId")
                        .HasColumnType("bigint");

                    b.HasKey("ArticleId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("article_tags", (string)null);
                });

            modelBuilder.Entity("Avw.Data.Entities.CasualtyLink", b =>
                {
                    b.Property<string>("ServiceNumber")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("ContactId")
                        .HasColumnType("int");

                    b.HasKey("ServiceNumber", "ContactId");

                    b.HasIndex("ContactId");

                    b.ToTable("casualty_links", (string)null);
                });

            modelBuilder.Entity("Avw.Data.Entities.CasualtySubmission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CasualtyType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<int>("ContactId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Handled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("HandledUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LegacyId")
                        .HasColumnType("int");

                    b.Property<string>("ServiceNumber")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<long?>("SubmittedById")
                        .HasColumnType("bigint");

                    b.Property<string>("SubmittedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("LegacyId");

                    b.HasIndex("Handled", "CreatedUtc");

                    b.ToTable("casualty_submissions", (string)null);
                });

            modelBuilder.Entity("Avw.Data.Entities.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Avw.Data.Entities.FeedbackMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Handled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("HandledUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Handled", "CreatedUtc");

                    b.ToTable("feedback", (string)null);
                });

            modelBuilder.Entity("Avw.Data.Entities.IncidentMedia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("AttachedById")
                        .HasColumnType("bigint");

                    b.Property<string>("AuthorEmailHash")
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<string>("AuthorName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("ContactId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateTaken")
                        .HasColumnType("date");

                    b.Property<double?>("Lat")
                        .HasColumnType("double");

                    b.Property<int?>("LegacyId")
                        .HasColumnType("int");

                    b.Property<int>("LegacyLikes")
                        .HasColumnType("int");

                    b.Property<double?>("Lon")
                        .HasColumnType("double");

                    b.Property<long>("MediaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AuthorEmailHash");

                    b.HasIndex("ContactId");

                    b.HasIndex("LegacyId");

                    b.HasIndex("MediaId");

                    b.HasIndex("ContactId", "MediaId")
                        .IsUnique();

                    b.HasIndex("Lat", "Lon");

                    b.ToTable("incident_media", (string)null);
                });

            modelBuilder.Entity("Avw.Data.Entities.IncidentNote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int?>("ApprovedVersionNo")
                        .HasColumnType("int");

                    b.Property<string>("AuthorEmailHash")
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<long?>("AuthorId")
                        .HasColumnType("bigint");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("CommentsOpen")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ContactId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LatestVersionNo")
                        .HasColumnType("int");

                    b.Property<int?>("LegacyId")
                        .HasColumnType("int");

                    b.Property<long?>("ModeratedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModeratedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorEmailHash");

                    b.HasIndex("AuthorId");

                    b.HasIndex("LegacyId");

                    b.HasIndex("Status");

                    b.HasIndex("ContactId", "Status");

                    b.ToTable("incident_notes", (string)null);
                });

            modelBuilder.Entity("Avw.Data.Entities.IncidentNoteVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("EditedById")
                        .HasColumnType("bigint");

                    b.Property<string>("EditedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<long>("NoteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NoteId", "VersionNo")
                        .IsUnique();

                    b.ToTable("incident_note_versions", (string)null);
                });

            modelBuilder.Entity("Avw.Data.Entities.MediaAsset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Credit")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long>("UploadedById")
                        .HasColumnType("bigint");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .IsUnique();

                    b.HasIndex("UploadedById");

                    b.ToTable("media_assets", (string)null);
                });

            modelBuilder.Entity("Avw.Data.Entities.MediaLike", b =>
                {
                    b.Property<long>("MediaId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MediaId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("media_likes", (string)null);
                });

            modelBuilder.Entity("Avw.Data.Entities.NoteComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AuthorEmailHash")
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<long?>("AuthorId")
                        .HasColumnType("bigint");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LegacyId")
                        .HasColumnType("int");

                    b.Property<long>("NoteId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AuthorEmailHash");

                    b.HasIndex("LegacyId");

                    b.HasIndex("NoteId", "CreatedUtc");

                    b.ToTable("note_comments", (string)null);
                });

            modelBuilder.Entity("Avw.Data.Entities.Poi", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<int?>("Established")
                        .HasColumnType("int");

                    b.Property<double>("Lat")
                        .HasColumnType("double");

                    b.Property<double>("Lon")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<bool>("Visible")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("Visible");

                    b.ToTable("points_of_interest", (string)null);
                });

            modelBuilder.Entity("Avw.Data.Entities.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Avw.Data.Entities.Tribute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AuthorEmailHash")
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<long?>("AuthorId")
                        .HasColumnType("bigint");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LegacyId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ServiceNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorEmailHash");

                    b.HasIndex("LegacyId");

                    b.HasIndex("ServiceNumber", "CreatedUtc");

                    b.ToTable("tributes", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("longtext");

                    b.Property<string>("Xml")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("Avw.Data.Entities.Article", b =>
                {
                    b.HasOne("Avw.Data.Entities.AppUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Avw.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Avw.Data.Entities.MediaAsset", "FeaturedMedia")
                        .WithMany()
                        .HasForeignKey("FeaturedMediaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Avw.Data.Entities.Article", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Author");

                    b.Navigation("Category");

                    b.Navigation("FeaturedMedia");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Avw.Data.Entities.ArticleRevision", b =>
                {
                    b.HasOne("Avw.Data.Entities.Article", "Article")
                        .WithMany("Revisions")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avw.Data.Entities.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Avw.Data.Entities.ArticleTag", b =>
                {
                    b.HasOne("Avw.Data.Entities.Article", "Article")
                        .WithMany("Tags")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avw.Data.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Avw.Data.Entities.IncidentMedia", b =>
                {
                    b.HasOne("Avw.Data.Entities.MediaAsset", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("Avw.Data.Entities.IncidentNote", b =>
                {
                    b.HasOne("Avw.Data.Entities.AppUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Avw.Data.Entities.IncidentNoteVersion", b =>
                {
                    b.HasOne("Avw.Data.Entities.IncidentNote", "Note")
                        .WithMany("Versions")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");
                });

            modelBuilder.Entity("Avw.Data.Entities.MediaAsset", b =>
                {
                    b.HasOne("Avw.Data.Entities.AppUser", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("Avw.Data.Entities.MediaLike", b =>
                {
                    b.HasOne("Avw.Data.Entities.MediaAsset", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avw.Data.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Avw.Data.Entities.NoteComment", b =>
                {
                    b.HasOne("Avw.Data.Entities.IncidentNote", "Note")
                        .WithMany("Comments")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");
                });

            modelBuilder.Entity("Avw.Data.Entities.Article", b =>
                {
                    b.Navigation("Revisions");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Avw.Data.Entities.IncidentNote", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
