apiVersion: v1
kind: Service
metadata:
  name: {{ include "avw-web.name" . }}
  labels:
    {{- include "avw-web.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "avw-web.selector" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
