/**
 * Defines constants to enable referencing and serialisation of basemap layer types
 */
BM.BasemapType = {
	mapbox: {
		terrain: 'mapbox-terrain',
		satellite: 'mapbox-satellite',
		light: 'mapbox-light',
		dark: 'mapbox-dark'
	}
};

/**
 * Initialises a basemap layer. Invokes the specified creation function immediately, but does not add the layer to the map.
 * @param basemapType
 * @param {string} title
 * @param {string} caption
 * @param creationFn - Function that handles the creation of the layer object. Requires one parameter: BM.Layer.Basemap, which is the layer wrapper
 * @constructor
 */
BM.Layer.Basemap = function(basemapType, title, caption, creationFn)
{
	this.basemapType = basemapType;
	this.title = title;
	this.caption = caption;
	this.olLayer = null;
	this.uiControl = null;                                  // Set by BasemapController.addBasemap()

	if (creationFn)
		creationFn(this);
};

/**
 * Returns whether the basemap layer exists on the map
 * @returns {boolean}
 */
BM.Layer.Basemap.prototype.isActive = function()
{
	if (this.olLayer)
		return this.olLayer.getVisible();
	else
		return false;
};

/**
 * Enable/disable the basemap layer and set the layer's button state
 * @param {boolean} activeState
 */
BM.Layer.Basemap.prototype.setActive = function(activeState)
{
	if (this.olLayer && this.uiControl)
	{
		if (activeState)
		{
			if (!this.isActive())
			{
				this.olLayer.setVisible(true);
				BM.StateManagement.replaceState();
			}

			this.uiControl
				.prop('checked', true)
				.button('refresh');
		}
		else
		{
			if (this.isActive())
				this.olLayer.setVisible(false);

			this.uiControl
				.prop('checked', false)
				.button('refresh');
		}
	}
	else
	{
		console.log('Warning: Attempted to add an uninitialised basemap: "' + this.basemapType + '"');
	}
};

BM.Layer.Basemap.prototype.addToMap = function()
{
	if (this.olLayer)
		BM.map.addLayer(this.olLayer);
};

BM.Layer.Basemap.prototype.removeFromMap = function()
{
	if (this.olLayer)
		BM.map.removeLayer(this.olLayer);
};

/**
 * Contains BM.Layer.Basemap instances and handles UI switching between layers
 * @param containerElement - jQuery object for the element that will contain the UI controls generated by this class
 * @constructor
 */
BM.BasemapController = function(containerElement)
{
	this.containerElement = containerElement;
	this.basemapLayers = [];

	var form = $(document.createElement('form'));
	this.containerElement.append(form);
	this.containerElement.controlgroup();
};

/**
 * Adds an existing basemap to the controller
 * @param {BM.Layer.Basemap} basemap
 * @returns {BM.BasemapController}
 */
BM.BasemapController.prototype.addBasemap = function(basemap)
{
	var self = this;
	var form = this.containerElement.find('form');
	var existingControlCount = form.children('input').length;
	var buttonID = 'basemap-button-' + existingControlCount;
	var button = $(document.createElement('input'));
	var label = $(document.createElement('label'));

	form.attr('id', 'basemap-selector-form');
	button
		.attr('type', 'radio')
		.attr('id', buttonID)
		.attr('name', 'basemap-selector')
		.attr('title', basemap.caption)
		.attr('class', 'basemap-button')
		.appendTo(form)
		.on('click', function() {
			self.selectBasemap(basemap);
		});
	label
		.attr('for', buttonID)
		.text(basemap.title)
		.appendTo(form);

	form.find('input').checkboxradio({
		icon: false
	});

	this.containerElement.controlgroup('refresh');
	basemap.uiControl = button;
	this.basemapLayers.push(basemap);
	basemap.addToMap();

	return this;
};

/**
 * Returns the basemap that exists on the map. Assumes that only one basemap can be active at a time.
 * @returns {BM.Layer.Basemap}
 */
BM.BasemapController.prototype.getActiveBasemap = function()
{
	for(var i = 0; i < this.basemapLayers.length; i++)
	{
		var layer = this.basemapLayers[i];
		if (layer.isActive())
			return layer;
	}

	return null;
};

/**
 * Retrieves a basemap by its type
 * @param {BM.BasemapType,*} basemapType
 * @return {BM.Layer.Basemap}
 */
BM.BasemapController.prototype.getBasemap = function(basemapType)
{
	var basemap = null;
	$.each(this.basemapLayers, function(i, item) {
		if (item.basemapType === basemapType)
		{
			basemap = item;
			return true;
		}
	});

	return basemap;
};

/**
 * Adds the selected basemap type to the map, while removing all others
 * @param {BM.Layer.Basemap} basemap
 */
BM.BasemapController.prototype.selectBasemap = function(basemap)
{
	$.each(this.basemapLayers, function(i, item) {
		item.setActive(item === basemap);
	});
};

/**
 * Creates a comma-separated list of enabled
 * @returns {string}
 */
BM.BasemapController.prototype.serialiseState = function()
{
	var activeBasemap = this.getActiveBasemap();
	if (activeBasemap)
		return activeBasemap.basemapType;
	else
		return "";
};

BM.BasemapController.prototype.parseState = function(state)
{
	if (state)
		this.selectBasemap(this.getBasemap(state));
};