/**
 * Used to identify each layer and enable serialisation of layer state
 */
BM.LayerType = {
	military: {
		shaded1atf: 'raster-shaded1atf',
		classic1atf: 'raster-classic1atf'
	},
	detail: {
		all: 'detail-all'
	},
	contact: {
		clustered: 'contact-clustered',
		individual: 'contact-individual',
		airSorties: 'air-sorties',
		navalFireMissions: 'naval-fire-missions'
	},
	media: {
		iconsByLocation: 'media-icons-by-loc'
	},
	poi: {
		fsb: 'poi-fsb'
	},
	concentration: {
		incidents: 'conc-incidents',
		uaIncidentHits: 'conc-ua-incid-hits'
	}
};

/**
 * Identifies layer groups. String value is used as layer group control label
 */
BM.LayerGroupType = {
	militaryMap: 'military-maps',
	detail: 'detail',
	concentration: 'concentrations',
	contact: 'contacts',
	media: 'media',
	poi: 'poi'
};

/**
 * Layer class encapsulating a LeafletJS layer and properties allowing its visibility to be changed via the UI
 * @param {BM.LayerType} type - LayerType unique descriptor, allowing the layer to be referenced
 * @param {string} title - Label to display for the layer's checkbox
 * @param {number} [zIndex] - Z order relative to the group
 * @param {{}} [layerOptions] - User-configurable options for the layer
 * @constructor
 * @class
 */
BM.Layer = function(type, title, zIndex, layerOptions)
{
	var self = this;
	this.olLayer = null;                           // Initialised and generated by external function at 'layerGenerationFn'
	this.type = type;
	this.title = title;                            // Title used to describe the layer in the UI
	this.zIndex = zIndex;
	this.parentGroup = null;
	this.generationInProgress = false;
	this.silentRegeneration = false;				// If TRUE, regeneration is performed without any progress feedback

	/**
	 * Common properties that are added to olLayer after initialisation.
	 * Subclasses should add/change these properties as required.
	 * @type {{}}
	 */
	this.layerProperties = {};

	/**
	 * User customisation controls that are defined by subclasses prior to invoking BM.Layer constructor
	 * @type {{BM.LayerOption}}
	 */
	this.layerOptions = layerOptions || {};
	this.layerOptions.opacity = new BM.LayerOption.Slider('Opacity', {
		min: 1,
		max: 100,
		onChange: function(oldValue, newValue) {
			if (self.olLayer)
				self.olLayer.setOpacity(newValue / 100);
		}
	});

	var layerControlID = 'layer-' + this.type;
	this.selectorControlContainer = $(document.createElement('div'));
	this.selectorControl = $(document.createElement('input'))
		.addClass('layer-selector-control')
		.attr('id', layerControlID)
		.appendTo(this.selectorControlContainer);
	$(document.createElement('label'))
		.addClass('layer-selector-control')
		.attr('for', layerControlID)
		.text(self.title)
		.appendTo(this.selectorControlContainer);

	if (this.layerOptions)
	{
		this.optionContainer = $(document.createElement('div'))
			.addClass('layer-option-container')
			.appendTo(this.selectorControlContainer);
		this.optionTooltip = $(document.createElement('div'))
			.addClass('layer-options-tooltip-content')
			.appendTo(this.optionContainer);
		this.optionButton = $(document.createElement('div'))
			.addClass('button')
			.append('<span class="fa fa-cog"></span>')
			.appendTo(this.optionContainer)
			.tooltipster({
				content: this.optionTooltip,
				contentCloning: false,
				interactive: true,
				side: 'left',
				distance: 0,
				minWidth: 200,
				theme: 'tooltipster-light battlemap-tooltip-light layer-options-tooltip',
				trigger: 'custom',
				triggerOpen: 'custom',
				triggerClose: 'custom'
			})
			.click(function() {
				if ($(this).hasClass('active'))
					self.setOptionsVisibility(false);
				else
					self.setOptionsVisibility(true);
			});

		// Close the tooltip if the right sidebar is closed or the sidebar panel is changed
		$('body').on('bm:right-sidebar.visibilityChanged, bm:right-sidebar-panel.show, bm:right-sidebar-panel.hide', function(event) {
			self.setOptionsVisibility(false);
		});

		if (!this.isChecked())
			this.optionButton.hide();

		// For each layer option control, render it within the tooltip container
		for (var key in this.layerOptions)
		{
			this.layerOptions[key].render(self.optionTooltip);
		}
	}
};

/**
 * Opens or closes the layer options tooltip
 * @param {boolean} visible
 */
BM.Layer.prototype.setOptionsVisibility = function(visible)
{
	if (visible)
	{
		// Close any other open layer option tooltips
		$('.layer-option-container').find('.button')
			.removeClass('active')
			.tooltipster('close');

		this.optionButton.tooltipster('open');
		this.optionButton.addClass('active');
	}
	else
	{
		this.optionButton.tooltipster('close');
		this.optionButton.removeClass('active');
	}
};

/**
 * Prototype method to generate the layer. This could involve connecting to a tile source or creating markers based on an AJAX query.
 * To be implemented by derived classes.
 * @param [callback]
 * @abstract
 */
BM.Layer.prototype.generate = function(callback) {};

/**
 * Regenerates the layer. This is used as the public interface method to perform layer generation
 * @param [callback]
 * @param {boolean} [closeLoadingIndicatorWhenDone] - If this layer is being regenerated along with all other layers, do not close the indicator between each layer regeneration
 */
BM.Layer.prototype.regenerate = function(callback, closeLoadingIndicatorWhenDone)
{
	var self = this;
	var regenerationCompleted = function() {
		if (callback)
			callback();
	};

	// Generate if the layer selector is checked or init is in progress
	if ((this.isChecked() || this.parentGroup.layerController.initInProgress) && !this.generationInProgress)
	{
		var generate = function() {
			self.generationInProgress = true;
			self.generate(function() {
				self.generationInProgress = false;
				if (!BM.StateManagement.stateRestorationInProgress())
				{
					if (closeLoadingIndicatorWhenDone)
						BM.LoadingProgress.hide(regenerationCompleted);
					else
						regenerationCompleted();
				}
				else
				{
					regenerationCompleted();
				}
			});
		};

		if (!this.silentRegeneration)
		{
			BM.LoadingProgress.init('Generating layer', this.parentGroup.title + ' | ' + this.title, true);
			BM.LoadingProgress.show(function () {
				generate();
			});
		}
		else
		{
			generate();
		}
	}
	else
	{
		regenerationCompleted();
	}
};

BM.Layer.prototype.stateChanged = function()
{
	// TODO: This is not being fired when the group state is changed. Fix by making layers/groups event-driven

	// State changes are handled by LayerController.restoreState() during initialisation
	if (!this.parentGroup.layerController.initInProgress)
	{
		if (this.isChecked())
			this.addToMap(true);
		else
			this.removeFromMap();

		BM.StateManagement.replaceState();
	}

	if (this.optionButton)
	{
		if (this.isChecked())
		{
			this.optionButton.show();
		}
		else
		{
			this.optionButton.hide();
			this.setOptionsVisibility(false);
		}
	}
};

BM.Layer.prototype.check = function(callback)
{
	this.selectorControl.iCheck('check', callback);
};

BM.Layer.prototype.uncheck = function(callback)
{
	this.selectorControl.iCheck('uncheck', callback);
};

BM.Layer.prototype.isChecked = function()
{
	return this.selectorControl.first().prop('checked') === true;
};

/**
 * Adds the layer to the map and optionally regenerates it before doing so
 * @param {boolean} [regenerateLayer]
 */
BM.Layer.prototype.addToMap = function(regenerateLayer)
{
	var self = this;
	var addLayerToMap = function() {
		if (self.olLayer)
		{
			// Incorporate custom properties into the olLayer object
			self.olLayer.setProperties(self.layerProperties);
			self.olLayer.setZIndex(self.parentGroup.zIndex + (self.zIndex ? self.zIndex : 0));

			if (!self.olLayer.getVisible())
				self.olLayer.setVisible(true);

			self.notifyLayerEnabled(true);
		}
		else
		{
			console.log('Error: Layer of type "' + self.type + '" is not ready. There may have been an error during generation.');
		}
	};

	// Add the layer to the map after it has been completed and callback fired
	if (regenerateLayer)
		return this.regenerate(addLayerToMap, true);

	// Safeguard in case no callback was defined
	addLayerToMap();
};

/**
 * Removes the layer from the map
 */
BM.Layer.prototype.removeFromMap = function()
{
	if (this.olLayer)
	{
		if (this.olLayer.getVisible())
			this.olLayer.setVisible(false);

		this.notifyLayerEnabled(false);
	}
	else
	{
		console.log('Error: Layer of type "' + self.type + '" is not ready. There may have been an error during generation.');
	}
};

/**
 * Called when the layer is added/removed from the map
 * @param {boolean} enabled
 * @protected
 */
BM.Layer.prototype.notifyLayerEnabled = function(enabled)
{
	$('body').trigger($.Event('bm:layer.enabled', {
		layer: this,
		enabled: enabled
	}));
};

/**
 * A layer container shown as a clickable category-type heading in the layer panel.
 * LayerGroup instances are members of the LayerController class. Each layer must be contained by a group.
 * @param {BM.LayerGroupType} layerGroupType - Identifies the group control
 * @param {string} title - Label text to display for the group control
 * @param {string} caption - Caption text to display when hovering over the group selector control
 * @param {number} [zIndex] - Layers added to this group inherit this z index, unless otherwise specified by the layer constructor
 * @param {boolean} allowMultipleActiveLayers - Whether to represent layer controls as checkboxes (TRUE) or radio buttons (FALSE)
 * @constructor
 * @class
 */
BM.LayerGroup = function(layerGroupType, title, caption, zIndex, allowMultipleActiveLayers)
{
	var self = this;
	this.layerController = null;
	this.layers = [];
	this.layerGroupType = layerGroupType;
	this.title = title;
	this.caption = caption;
	this.zIndex = zIndex;
	this.allowMultipleActiveLayers = allowMultipleActiveLayers;           // Whether multiple visible layers in this group are permitted

	var selectorControlID = 'layer-group-' + this.layerGroupType;
	this.selectorControlContainer = $(document.createElement('div'))
		.addClass('layer-selector-container');
	this.selectorControl = $(document.createElement('input'))
		.addClass('layer-selector-control')
		.attr('type', 'checkbox')
		.attr('id', selectorControlID)
		.appendTo(this.selectorControlContainer)
		.on('ifToggled', function() {
			self.stateChanged();
		});
	$(document.createElement('label'))
		.addClass('layer-selector-control')
		.attr('for', selectorControlID)
		.text(this.title)
		.appendTo(this.selectorControlContainer);

	this.layerControlContainer = $(document.createElement('div'))
		.addClass('layer-group-container')
		.appendTo(this.selectorControlContainer);
};

/**
 * Adds a layer to the group
 * @param {BM.Layer} layer
 * @returns {BM.LayerGroup}
 */
BM.LayerGroup.prototype.addLayer = function(layer)
{
	var self = this;
	var controlType = this.allowMultipleActiveLayers ? 'checkbox' : 'radio';

	layer.parentGroup = this;
	layer.selectorControl
		.attr('type', controlType)
		.attr('name', this.allowMultipleActiveLayers ? '' : this.layerGroupType)
		.attr('value', this.allowMultipleActiveLayers ? '' : layer.type)
		.on('ifToggled', function() {
			layer.stateChanged();
			self.layerStateChanged(layer, layer.isChecked());
		});

	layer.selectorControlContainer.appendTo(this.layerControlContainer);
	BM.initICheckUIControl(layer.selectorControl);
	this.layers.push(layer);

	return this;
};

/**
 * For radio button groups (single choice), returns the radio controlset value. For multi-choice groups, returns NULL
 */
BM.LayerGroup.prototype.getValue = function()
{
	if (this.allowMultipleActiveLayers)
		return null;
	else
	{
		var radioControl = this.layerControlContainer.find('input:radio:checked');
		if (radioControl)
			return radioControl.val();
		else
			return null;
	}
};

/**
 * Called when the checked state of a layer control is changed. If a group's layers are deselected, the parent group is also collapsed
 * @param {BM.Layer} layer
 * @param {boolean} newEnabledState
 */
BM.LayerGroup.prototype.layerStateChanged = function(layer, newEnabledState)
{
	if (!newEnabledState)
	{
		// A radio controls series cannot be 'unchecked', so only attempt to close the group if it is not a radio button group
		if (this.allowMultipleActiveLayers)
		{
			var layerControls = this.layerControlContainer.find('input:checked');

			// All subordinate layer controls are now unchecked, so collapse the parent group
			if (layerControls.length === 0)
				this.selectorControl.iCheck('uncheck');
		}
	}
	else
	{
		// Check the group control if it isn't already
		if (!this.isChecked())
			this.check();

		BM.ActivityLogging.logEvent(BM.LogEventTypes.selectedLayer, null, layer.type);
	}
};

BM.LayerGroup.prototype.stateChanged = function()
{
	var i;
	if (!this.isChecked())
	{
		// New state is disabled, so remove all selected layers from the map
		this.layerControlContainer.hide(200);

		// Do not process any further if initialising
		if (!this.layerController.initInProgress)
		{
			for (i = 0; i < this.layers.length; i++)
			{
				var layer = this.layers[i];
				if (layer.olLayer)
					this.layers[i].removeFromMap();
			}
		}
	}
	else
	{
		// Group is now shown, so restore the currently selected layers
		this.layerControlContainer.show(200);
		var layersEnabled = false;

		if (!this.layerController.initInProgress)
		{
			for (i = 0; i < this.layers.length; i++)
			{
				if (this.layers[i].isChecked())
				{
					this.layers[i].addToMap(false);
					layersEnabled = true;
				}
			}

			// If no layers are enabled and this group has either one element or is a single-choice group (i.e. radio controls), enable the first layer by default
			if (this.layers.length === 1 || (!this.allowMultipleActiveLayers && !layersEnabled))
				this.layers[0].check();
		}
	}

	if (!this.layerController.initInProgress)
	{
		// Trigger listening components when the group enabled state is changed (not yet implemented)
		/*this.layerController.containerElement.trigger(BM.Events.layerContactsToggle, {
			changedGroup: this,
			changedLayer: null,
			newState: newEnabledState
		});*/

		BM.StateManagement.replaceState();
	}
};

/**
 * @param [callback]
 */
BM.LayerGroup.prototype.check = function(callback)
{
	var self = this;
	this.selectorControl.iCheck('check', function() {
		self.layerControlContainer.show(200, callback);
	});
};

/**
 * @param [callback]
 */
BM.LayerGroup.prototype.uncheck = function(callback)
{
	var self = this;
	this.selectorControl.iCheck('uncheck', function() {
		self.layerControlContainer.hide(200, callback);
	});
};

BM.LayerGroup.prototype.isChecked = function()
{
	return this.selectorControl.prop('checked') === true;
};

/**
 * Generates the UI for layers as they are added to groups within the controller. Can serialise layer state and allows for
 * layers to be shown/hidden
 * @param containerElement
 * @constructor
 * @class
 */
BM.LayerController = function(containerElement)
{
	this.containerElement = containerElement;                   // jQuery object for containing all UI elements generated by the LayerController
	this.initInProgress = false;                                // Set during initialisation. Stops multiple replaceState calls from occurring

	if (!containerElement)
		console.log('Error: BM.LayerController was provided an invalid container element');

	this.layerGroups = [];
};

/**
 * Creates a new layer group and adds it to the controller
 * @param {BM.LayerGroup} layerGroup - The initialised layer group object to add to the controller
 * @returns {BM.LayerGroup}
 */
BM.LayerController.prototype.addGroup = function(layerGroup)
{
	this.layerGroups.push(layerGroup);
	this.containerElement.append(layerGroup.selectorControlContainer);
	BM.initICheckUIControl(layerGroup.selectorControl);
	layerGroup.layerController = this;

	return layerGroup;
};

// TODO: Implement group tooltips

/**
 * Returns a LayerGroup from its group type
 * @param {BM.LayerGroupType} groupType
 * @returns {BM.LayerGroup}
 */
BM.LayerController.prototype.getGroup = function(groupType)
{
	for(var i = 0; i < this.layerGroups.length; i++)
	{
		var group = this.layerGroups[i];
		if (group.layerGroupType === groupType)
			return group;
	}

	console.log('Warning: LayerController.getGroup could not find the layer group "' + groupType + '"');
	return null;
};

/**
 * Retrieves a BM.Layer by its LayerType
 * @param {BM.LayerType} layerType
 * @returns {BM.Layer}
 */
BM.LayerController.prototype.getLayer = function(layerType)
{
	for(var i = 0; i < this.layerGroups.length; i++)
	{
		var group = this.layerGroups[i];
		for(var j = 0; j < group.layers.length; j++)
		{
			var layer = group.layers[j];
			if (layer.type === layerType)
				return layer;
		}
	}

	return null;
};

/**
 * Refreshes the selected layer in a single-choice group (must have LayerGroup.allowMultipleActiveLayers set to FALSE.
 * Method returns NULL if this property is TRUE (i.e. checkbox groups)
 * @param {BM.LayerType} groupType
 * @returns {BM.Layer}
 */
BM.LayerController.prototype.getSelectedLayerInGroup = function(groupType)
{
	var group = this.getGroup(groupType);
	if (group)
	{
		if (group.isChecked() && !group.allowMultipleActiveLayers)
		{
			for (var i = 0; i < group.layers.length; i++)
			{
				var layer = group.layers[i];
				if (layer.isChecked())
				{
					return layer;
				}
			}

		}
	}

	return null;
};

/**
 * Creates a comma-separated list string containing the layer types that are currently selected (enabled)
 * @returns {string}
 */
BM.LayerController.prototype.serialiseState = function()
{
	var serialisedState = "";
	for(var i = 0; i < this.layerGroups.length; i++)
	{
		var group = this.layerGroups[i];

		// Group is selected, so process its contained layers
		if (group.isChecked())
		{
			for (var j = 0; j < group.layers.length; j++)
			{
				var layer = group.layers[j];

				// Layer is checked, so add its type to the serialised string
				if (layer.isChecked())
					serialisedState += (serialisedState.length > 0 ? ',' : '') + layer.type;
			}
		}
	}

	return serialisedState;
};

/**
 * Restores layer state from a serialised string containing comma-separated layer types
 * @param {string} serialisedState
 * @param callback - Invoked with the number of layers successfully processed
 */
BM.LayerController.prototype.parseState = function(serialisedState, callback)
{
	var self = this;
	var layersProcessed = 0;

	// Block calls to this method if initialisation is already in progress
	if (serialisedState && !this.initInProgress)
	{
		// Stop multiple calls to replaceState as controls are checked
		this.initInProgress = true;

		var selectedLayers = serialisedState.split(',');

		// Recursively process each layer in sequence, waiting for regeneration to occur each time
		var processLayerType = function(layerTypes)
		{
			if (layerTypes.length < 1)
			{
				self.initInProgress = false;
				BM.LoadingProgress.hide();
				if (callback)
					return callback(layersProcessed);
			}

			var layerType = layerTypes.pop();

			// TODO: Implement clustered layer or remove this code once old deep-link URLs have been updated
			if (layerType == BM.LayerType.contact.clustered)
				layerType = BM.LayerType.contact.individual;

			var layer = self.getLayer(layerType);
			if (layer)
			{
				layersProcessed++;

				// Layer is not currently enabled, so generate it and add to the map
				if (!layer.isChecked())
				{
					console.log('Processing layer type: ' + layerType);
					layer.check();
					layer.regenerate(function() {
						console.log('Generated layer: ' + layerType);
						layer.addToMap(false);
						processLayerType(layerTypes);
					}, false);
				}
				else
				{
					// Layer is already enabled, so do not add it again
					processLayerType(layerTypes);
				}
			}
			else
			{
				console.log('Warning: Invalid layer type specified: "' + layerType + '"');
				processLayerType(layerTypes);
			}
		};

		processLayerType(selectedLayers);
	}
	else if(this.initInProgress)
	{
		console.log('Warning: Multiple calls to LayerController.parseState() detected');
		if (callback)
			callback(0);
	}
};

/**
 * Shows a particular layer, as identified by its LayerType
 * @param {BM.LayerType} layerType
 */
BM.LayerController.prototype.showLayer = function(layerType)
{
	var layer = this.getLayer(layerType);
	if (layer)
		layer.check();
};

/**
 * Hides a particular layer
 * @param {BM.LayerType} layerType
 */
BM.LayerController.prototype.hideLayer = function(layerType)
{
	var layer = this.getLayer(layerType);
	if (layer)
		layer.uncheck();
};

/**
 * Returns whether the specified layer is checked (enabled)
 * @param {BM.LayerType} layerType
 * @returns {boolean}
 */
BM.LayerController.prototype.isLayerChecked = function(layerType)
{
	var layer = this.getLayer(layerType);
	if (layer)
		return layer.isChecked();
	else
		return false;
};

/**
 *
 * @param {BM.LayerGroupType} groupType
 * @returns {boolean}
 */
BM.LayerController.prototype.isGroupChecked = function(groupType)
{
	var group = this.getGroup(groupType);
	if (group)
		return group.isChecked();
	else
		return false;
};

/**
 * Refreshes the layer by calling the regeneration function associated with it
 * @param {BM.LayerType} layerType
 * @param callback
 */
BM.LayerController.prototype.regenerateLayer = function(layerType, callback)
{
	var layer = this.getLayer(layerType);
	if (layer)
	{
		if (layer.isChecked())
		{
			layer.regenerate(function () {
				if (callback)
					return callback();
			}, true);
		}
	}

	if (callback)
		callback();
};

/**
 * Refreshes the selected layer in a single-choice group (must have LayerGroup.allowMultipleActiveLayers set to FALSE.
 * Method does nothing on if this property is TRUE (i.e. checkbox groups)
 * @param {BM.LayerType} groupType
 * @param [callback]
 */
BM.LayerController.prototype.regenerateSelectedLayerInGroup = function(groupType, callback)
{
	var layer = this.getSelectedLayerInGroup(groupType);
	if (layer)
	{
		layer.regenerate(function () {
			if (callback)
				callback();
		}, true);
	}
	else
	{
		if (callback)
			callback();
	}
};

/**
 * Regenerates all currently enabled layers
 * @param [callback]
 */
BM.LayerController.prototype.regenerateAllLayers = function(callback)
{
	var self = this;

	// Starts the recursive process by triggering the first layer in the current group to be processed
	var processGroup = function(groupIndex)
	{
		if (groupIndex >= self.layerGroups.length)
		{
			if (callback)
			{
				BM.LoadingProgress.hide();
				return callback();
			}
		}

		processLayer(groupIndex, self.layerGroups[groupIndex].layers, 0);
	};

	// Processes each layer in the current group
	var processLayer = function(groupIndex, layers, layerIndex)
	{
		if (layerIndex >= layers.length)
			return processGroup(groupIndex + 1);

		var layer = layers[layerIndex];
		layer.regenerate(function() {
			processLayer(groupIndex, layers, layerIndex + 1);
		}, false);
	};

	// Start recursion from the first group until all groups and layers have been processed
	processGroup(0);
};