apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "avw-api.name" . }}-map
  labels:
    {{- include "avw-api.labels" . | nindent 4 }}
data:
  map.json: |
    {{- dict "Map" (dict
        "Center" .Values.map.center
        "Zoom" .Values.map.zoom
        "Basemaps" .Values.map.basemaps
        "Overlays" .Values.map.overlays
        "Terrain" .Values.map.terrain) | toPrettyJson | nindent 4 }}
