{{- if .Values.secrets.create }}
# For local clusters only. In real environments create the Secret out of band.
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "avw-api.secretName" . }}
  labels:
    {{- include "avw-api.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets.values }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
