apiVersion: v1
kind: Service
metadata:
  name: {{ include "avw-api.name" . }}
  labels:
    {{- include "avw-api.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "avw-api.selector" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
