@echo off

if exist ./src/js/bm/minified/battle-map.min.js del ./src/js/bm/minified/battle-map.min.js

echo Compiling from source
google-closure-compiler --compilation_level SIMPLE --jscomp_off suspiciousCode --js_output_file ./src/js/bm/minified/battle-map.min.js ^
./src/js/vendor/bowser/bowser.js ^
./src/js/vendor/angular/angular.js ^
./src/js/vendor/angular/angular-animate.js ^
./src/js/vendor/angular/angular-sanitize.js ^
./src/js/vendor/momentjs/moment-with-locales.js ^
./src/js/vendor/dropzone/dropzone.js ^
./src/js/vendor/videojs/video.js ^
./src/js/vendor/lightgallery/js/lightgallery.js ^
./src/js/vendor/lightgallery/modules/lg-autoplay.js ^
./src/js/vendor/lightgallery/modules/lg-fullscreen.js ^
./src/js/vendor/lightgallery/modules/lg-pager.js ^
./src/js/vendor/lightgallery/modules/lg-thumbnail.js ^
./src/js/vendor/lightgallery/modules/lg-video.js ^
./src/js/vendor/lightgallery/modules/lg-zoom.js ^
./src/js/vendor/clipboard/clipboard.min.js ^
./src/js/vendor/spin/spin.js ^
./src/js/vendor/spin/jquery.spin.js ^
./src/js/vendor/select2/js/select2.full.js ^
./src/js/vendor/jquery-ui/jquery-ui.js ^
./src/js/vendor/jquery-touchpunch/jquery.ui.touch-punch.js ^
./src/js/vendor/icheck/icheck.js ^
./src/js/vendor/jstree/jstree.js ^
./src/js/vendor/mcustom-scrollbar/jquery.mCustomScrollbar.js ^
./src/js/vendor/historyjs/jquery.history.js ^
./src/js/vendor/tooltipster/js/tooltipster.bundle.js ^
./src/js/vendor/tooltipster/js/plugins/tooltipster/tooltipster-discovery.js ^
./src/js/vendor/chroma/chroma.js ^
./src/js/vendor/highstock/highstock.src.js ^
./src/js/vendor/highstock/highcharts-3d.src.js ^
./src/js/vendor/highstock/themes/dark-unica.js ^
./src/js/vendor/highstock/highcharts-legend-highlighter.src.js ^
./src/js/bm/globals.js ^
./src/js/bm/window-manager/window-manager.js ^
./src/js/bm/services/utility.js ^
./src/js/bm/services/incident-note.js ^
./src/js/bm/services/honour-roll.js ^
./src/js/bm/services/media.js ^
./src/js/bm/directives/incident-note.js ^
./src/js/bm/directives/select-menu.js ^
./src/js/bm/directives/date-picker.js ^
./src/js/bm/directives/meta-tag-input.js ^
./src/js/bm/directives/tooltipped.js ^
./src/js/bm/directives/poppy-tooltip.js ^
./src/js/bm/directives/casualty-list-item.js ^
./src/js/bm/activity-logging.js ^
./src/js/bm/progress.js ^
./src/js/bm/quick-start-guide.js ^
./src/js/bm/timeline/timeline-series.js ^
./src/js/bm/timeline/timeline.js ^
./src/js/bm/timeline/timeline-track-type.js ^
./src/js/bm/timeline/timeline-track-type-unit.js ^
./src/js/bm/timeline/timeline-tracker.js ^
./src/js/bm/filter/filter.js ^
./src/js/bm/filter/filter-unit-tree.js ^
./src/js/bm/filter/filter-range-slider.js ^
./src/js/bm/filter/filter-text-box.js ^
./src/js/bm/filter/filter-single-select-list.js ^
./src/js/bm/filter/filter-multi-select-list.js ^
./src/js/bm/filter/filter-distinct-field-multi-select.js ^
./src/js/bm/filter/filter-distinct-field-single-select.js ^
./src/js/bm/filter/filter-incident-notes.js ^
./src/js/bm/chart/chart-options.js ^
./src/js/bm/chart/chart.js ^
./src/js/bm/chart/chart-incident-freq-date.js ^
./src/js/bm/chart/chart-incident-freq-time.js ^
./src/js/bm/chart/chart-battle-damage-date.js ^
./src/js/bm/chart/chart-battle-damage-time.js ^
./src/js/bm/chart/chart-loss-ratio-by-fired-first-by-date.js ^
./src/js/bm/chart/chart-loss-ratio-by-fired-first-by-time.js ^
./src/js/bm/chart/chart-weapon-rds-fired.js ^
./src/js/bm/chart/chart-weapon-cas-ranges.js ^
./src/js/bm/chart/chart-weapon-rds-fired-by-unit-task.js ^
./src/js/bm/chart/chart-weapon-rds-fired-per-en-cas.js ^
./src/js/bm/chart/chart-pers-tour-ages.js ^
./src/js/bm/chart/chart-pers-age-by-service.js ^
./src/js/bm/chart/chart-pers-age-of-death-by-service.js ^
./src/js/bm/marker-tooltip/marker-tooltip.js ^
./src/js/bm/marker-tooltip/marker-tooltip-incident.js ^
./src/js/bm/marker-tooltip/marker-tooltip-poi.js ^
./src/js/bm/marker-tooltip/marker-tooltip-air-sortie.js ^
./src/js/bm/marker-tooltip/marker-tooltip-sea-operation.js ^
./src/js/bm/layer/option/layer-option.js ^
./src/js/bm/layer/option/layer-option-slider.js ^
./src/js/bm/layer/option/layer-option-selectmenu.js ^
./src/js/bm/layer/layer.js ^
./src/js/bm/layer/layer-basemap.js ^
./src/js/bm/layer/layer-tile.js ^
./src/js/bm/layer/layer-icon.js ^
./src/js/bm/layer/layer-marker.js ^
./src/js/bm/layer/layer-marker-incident.js ^
./src/js/bm/layer/layer-marker-incident-circles.js ^
./src/js/bm/layer/layer-marker-media.js ^
./src/js/bm/layer/layer-marker-poi.js ^
./src/js/bm/layer/layer-air-operations.js ^
./src/js/bm/layer/layer-sea-operations.js ^
./src/js/bm/layer/layer-heatmap.js ^
./src/js/bm/layer/layer-heatmap-contact.js ^
./src/js/bm/layer/layers.js ^
./src/js/bm/guidance-line.js ^
./src/js/bm/incident-note/incident-note.js ^
./src/js/bm/casualty-info-dialog.js ^
./src/js/bm/search/search-source.js ^
./src/js/bm/search/search-source-es.js ^
./src/js/bm/search/search-source-es-operation.js ^
./src/js/bm/search/search-source-es-incident.js ^
./src/js/bm/search/search-source-es-incident-note.js ^
./src/js/bm/search/search-source-es-media.js ^
./src/js/bm/search/search-source-es-person.js ^
./src/js/bm/search/search.js ^
./src/js/bm/right-sidebar/right-sidebar-panel.js ^
./src/js/bm/right-sidebar/right-sidebar-panel-layers.js ^
./src/js/bm/right-sidebar/right-sidebar-panel-filters.js ^
./src/js/bm/right-sidebar/right-sidebar-panel-analytics.js ^
./src/js/bm/right-sidebar/right-sidebar-panel-notes.js ^
./src/js/bm/right-sidebar/right-sidebar-panel-honour-roll.js ^
./src/js/bm/right-sidebar/right-sidebar-panel-marker.js ^
./src/js/bm/right-sidebar/right-sidebar-panel-media-moderation.js ^
./src/js/bm/right-sidebar/right-sidebar.js ^
./src/js/bm/media/media.js ^
./src/js/bm/state-management.js ^
./src/js/bm/main-toolbox.js ^
./src/js/bm/battle-map.js

pause